"""add accounting carry forward report fields

Revision ID: 2e44efedf859
Revises: f757b188e1da
Create Date: 2026-06-30 00:49:19.962574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e44efedf859'
down_revision = 'f757b188e1da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carry_forward_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_invoice_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('source_invoice_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('source_invoice_due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('source_invoice_total_cents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_invoice_amount_remaining_cents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('old_invoice_status_before', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('old_invoice_status_after', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('carried_forward_amount_cents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('new_invoice_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('new_invoice_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('carry_forward_description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carry_forward_log', schema=None) as batch_op:
        batch_op.drop_column('carry_forward_description')
        batch_op.drop_column('new_invoice_number')
        batch_op.drop_column('new_invoice_id')
        batch_op.drop_column('carried_forward_amount_cents')
        batch_op.drop_column('old_invoice_status_after')
        batch_op.drop_column('old_invoice_status_before')
        batch_op.drop_column('source_invoice_amount_remaining_cents')
        batch_op.drop_column('source_invoice_total_cents')
        batch_op.drop_column('source_invoice_due_date')
        batch_op.drop_column('source_invoice_created')
        batch_op.drop_column('source_invoice_number')

    # ### end Alembic commands ###
