"""add pre-tax total to carry forward logs

Revision ID: 69bf009943be
Revises: 2e44efedf859
Create Date: 2026-07-28 02:00:46.361788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69bf009943be'
down_revision = '2e44efedf859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carry_forward_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_invoice_total_excluding_tax_cents', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carry_forward_log', schema=None) as batch_op:
        batch_op.drop_column('source_invoice_total_excluding_tax_cents')

    # ### end Alembic commands ###
