"""Add late fee logs

Revision ID: 7e701d33a36c
Revises: 822211181a87
Create Date: 2026-06-09 16:22:01.925427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e701d33a36c'
down_revision = '822211181a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('late_fee_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('invoice_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('invoice_item_id', sa.String(length=100), nullable=True),
    sa.Column('late_fee_month', sa.String(length=7), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('late_fee_log')
    # ### end Alembic commands ###
