"""Add livemode column to lof tables

Revision ID: 8c81df9bb139
Revises: 69bf009943be
Create Date: 2026-08-06 16:08:33.808604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c81df9bb139'
down_revision = '69bf009943be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_increase_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('livemode', sa.Boolean(), nullable=True))

    with op.batch_alter_table('carry_forward_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('livemode', sa.Boolean(), nullable=True))

    with op.batch_alter_table('late_fee_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('livemode', sa.Boolean(), nullable=True))

    with op.batch_alter_table('schedule_repair_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('livemode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_repair_log', schema=None) as batch_op:
        batch_op.drop_column('livemode')

    with op.batch_alter_table('late_fee_log', schema=None) as batch_op:
        batch_op.drop_column('livemode')

    with op.batch_alter_table('carry_forward_log', schema=None) as batch_op:
        batch_op.drop_column('livemode')

    with op.batch_alter_table('billing_increase_log', schema=None) as batch_op:
        batch_op.drop_column('livemode')

    # ### end Alembic commands ###
