"""add audit timestamps

Revision ID: 9393a41c95c9
Revises: b40d14b28b6f
Create Date: 2026-05-29 14:36:19.084352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9393a41c95c9'
down_revision = 'b40d14b28b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_increase_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('finished_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_billing_increase_log_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_increase_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_increase_log_run_id'))
        batch_op.drop_column('finished_at')
        batch_op.drop_column('started_at')

    # ### end Alembic commands ###
