"""add billing run control

Revision ID: b1aa86b1bd2c
Revises: 9393a41c95c9
Create Date: 2026-05-30 03:50:18.379532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1aa86b1bd2c'
down_revision = '9393a41c95c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_run_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_run_control')
    # ### end Alembic commands ###
