"""upgrade billing increase log audit fields

Revision ID: b40d14b28b6f
Revises: d3d9d8cb1bf2
Create Date: 2026-05-29 13:18:45.059840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40d14b28b6f'
down_revision = 'd3d9d8cb1bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_increase_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_id', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('increase_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('error_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('old_price_snapshot', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('stripe_snapshot', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_increase_log', schema=None) as batch_op:
        batch_op.drop_column('stripe_snapshot')
        batch_op.drop_column('old_price_snapshot')
        batch_op.drop_column('error_code')
        batch_op.drop_column('increase_percentage')
        batch_op.drop_column('product_id')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('run_id')

    # ### end Alembic commands ###
