"""Add billing increase log

Revision ID: d3d9d8cb1bf2
Revises: c0dc59973051
Create Date: 2026-05-29 11:53:25.163084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d9d8cb1bf2'
down_revision = 'c0dc59973051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_increase_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_price_id_old', sa.String(length=255), nullable=True),
    sa.Column('stripe_price_id_new', sa.String(length=255), nullable=True),
    sa.Column('old_amount', sa.Integer(), nullable=True),
    sa.Column('new_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    op.drop_table('billing_increase_log')
    # ### end Alembic commands ###
