"""add invoice number to late fee log

Revision ID: f757b188e1da
Revises: e80f2e9f4e6c
Create Date: 2026-06-22 11:28:55.291934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f757b188e1da'
down_revision = 'e80f2e9f4e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('late_fee_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('late_fee_log', schema=None) as batch_op:
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
